// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCotPUSIGri6DzstRGHR9DMFQfjOThKHTc',
    appId: '1:210172626435:web:5664d658e5125e4b093036',
    messagingSenderId: '210172626435',
    projectId: 'appdevgame-cec52',
    authDomain: 'appdevgame-cec52.firebaseapp.com',
    storageBucket: 'appdevgame-cec52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTi68OqGcURFARRI0Go7g-h-HN3xCA6q8',
    appId: '1:210172626435:android:1ae45ddd1df22a8b093036',
    messagingSenderId: '210172626435',
    projectId: 'appdevgame-cec52',
    storageBucket: 'appdevgame-cec52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBobashdhkkw9SdLqi6jVX12QY9R1rnCmo',
    appId: '1:210172626435:ios:c18e18211e648889093036',
    messagingSenderId: '210172626435',
    projectId: 'appdevgame-cec52',
    storageBucket: 'appdevgame-cec52.appspot.com',
    iosBundleId: 'com.example.appdev1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBobashdhkkw9SdLqi6jVX12QY9R1rnCmo',
    appId: '1:210172626435:ios:c18e18211e648889093036',
    messagingSenderId: '210172626435',
    projectId: 'appdevgame-cec52',
    storageBucket: 'appdevgame-cec52.appspot.com',
    iosBundleId: 'com.example.appdev1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCotPUSIGri6DzstRGHR9DMFQfjOThKHTc',
    appId: '1:210172626435:web:437a77577d6cc95c093036',
    messagingSenderId: '210172626435',
    projectId: 'appdevgame-cec52',
    authDomain: 'appdevgame-cec52.firebaseapp.com',
    storageBucket: 'appdevgame-cec52.appspot.com',
  );

}